version: '3.7'

services:
  now_playing:
    container_name: now_playing
    build: ./
    restart: always
    env_file: .env
    environment: 
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      LETSENCRYPT_HOST: ${LETSENCRYPT_HOST}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
      NODE_ENV: production
    expose:
      - ${NODE_PORT}

networks:
  default:
    external:
      name: nginx-proxy