version: '3.7'

services:
  now_playing:
    container_name: now_playing
    build: ./
    restart: always
    env_file: .env
    # volumes:
    #   - ./:/app
    #   - node_modules:/app/node_modules
    ports:
      - ${NODE_PORT}:${NODE_PORT}
  
# volumes:
#   node_modules: