version: '3.7'

services:
  now_playing:
    container_name: now_playing
    build: ./
    restart: always
    env_file: .env
    environment:
      NODE_ENV: production
    ports:
      - ${NODE_PORT}:${NODE_PORT}